apiVersion: apps/v1
kind: Deployment
metadata:
  name: fragment-gateway
  namespace: default
  labels:
    app: fragment-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fragment-gateway
  template:
    metadata:
      labels:
        app: fragment-gateway
    spec:
      containers:
        - name: fragment-gateway
          image: trutoo/fragment-gateway:1.2.3
          ports:
            - containerPort: 3000
              name: api
          env:
            - name: NODE_ENV
              value: production

            - name: REGISTRY
              value: https://npm.pkg.github.com

            - name: REGISTRY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: fragment-gateway
                  key: registry-token
