apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fragment-gateway
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: 'nginx'
  labels:
    app: fragment-gateway
spec:
  rules:
    - host: api.tapps.io
      http:
        paths:
          - path: /fragment-gateway/?(.*)
            backend:
              serviceName: fragment-gateway
              servicePort: http
