apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tapps-io
  namespace: default
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
  labels:
    app: tapps-io
spec:
  tls:
    - hosts:
        - tapps.io
        - api.tapps.io
        - content.tapps.io
        - analytics.tapps.io
      secretName: tapps-tls
  rules:
    - host: tapps.io
    - host: api.tapps.io
    - host: content.tapps.io
    - host: analytics.tapps.io
